name: Docker Publish

on:
    
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    types: [closed]
    branches: [ main ]

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write
  id-token: write
jobs:
  build-and-push:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Get version
        id: version
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/calcctl:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/calcctl:v${{ env.VERSION }}
          build-args: |
            VERSION=${{ env.VERSION }}
            
      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/calcctl
          short-description: "Command-line calculator utility"
          readme-filepath: ./README.md
          
      - name: Add dockerhub label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['dockerhub']
            })