name: Create GitHub Release

on:
  workflow_run:
    workflows: ["Deploy to Production"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  create-release:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history and tags
        
      - name: Get version
        id: version
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Build binary file
        run: |
          mkdir -p dist
          
          # Create proper executable script with correct indentation
          cat   > dist/calcctl << 'EOF'  
          #!/usr/bin/env python3
          from app_  ctl.calctl import main

          if       me__ ==   "__main__":
              main()
          EOF
                    
                    chmod +x dist/calcctl
                    ls -la dist/
                    
      - name: Generate release notes
        run: |
          # Get previous tag or default to v0.0.0 if none exists
          PREV_TAG=$(git tag --sort=-version:refname | head -n 1 || echo "v0.0.0")
          echo "## Changes since $PREV_TAG" > release-notes.md
          echo "" >> release-notes.md
          git log $PREV_TAG..HEAD --pretty=format:"* %s (%an)" >> release-notes.md
          echo "" >> release-notes.md
          echo "## Full CHANGELOG" >> release-notes.md
          echo "" >> release-notes.md
          cat CHANGELOG.md >> release-notes.md
          
      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          name: Version ${{ env.VERSION }}
          body_path: release-notes.md
          files: ./dist/calcctl
          draft: false
          prerelease: false