name: Security Check

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  security:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    
    - name: Check Python version
      run: |
        python --version
        python -m pip --version
    
    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety
    
    - name: Security code scan (Bandit)
      run: |
        bandit -r app_ctl/ -f json -o bandit-results.json
        
    - name: Dependency vulnerability check
      run: |
        safety check
        
    - name: Antivirus scan
      run: |
        sudo apt-get update
        sudo apt-get install -y clamav
        sudo freshclam
        clamscan --recursive --infected app_ctl/
    
    - name: Set PR security status
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.issues.addLabels({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['sec-passed']
          })