name: Test Self-Hosted Runner

on:
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  test:
    runs-on: self-hosted  # Использует ваш self-hosted runner
    
    steps:
    - uses: actions/checkout@v3
    - name: Run a test
      run: |
        echo "Hello from self-hosted runner!"
        echo "Runner name: $RUNNER_NAME"
        echo "OS: $(uname -a)"
        
    - name: Check Python version
      run: |
        python --version 