name: Test application
on:
  push:
    branches:
      - main
      - dev
      - workflow-development


jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          

      - name: Run tests
        run: |
          source .venv/bin/activate
          python -m unittest discover test/